apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pihole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pihole.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: 'ServerIP'
            value: {{ .Values.pihole.server | quote }}
          - name: 'DNS1'
            value: {{ .Values.pihole.dns1 | quote }}
          - name: 'DNS2'
            value: {{ .Values.pihole.dns2 | quote }}
          - name: TZ
            value: {{ .Values.pihole.timezone | quote }}
          {{- if .Values.pihole.password }}
          - name: WEBPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "pi-hole.fullname" . }}
                key: password
          {{- end }}
          - name: DNSMASQ_LISTENING
            value: {{ .Values.pihole.listening | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

          volumeMounts:
          - mountPath: "/etc/pihole"
            name: pihole-storage
            subPath: pihole/etc/pihole
          - mountPath: "/etc/dnsmasq.d"
            name: pihole-storage
            subPath: pihole/etc/dnsmasq.q                
              
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  
      volumes:
        - name: pihole-storage
          nfs:
            server: {{ .Values.nfs.server }} 
            path: {{ .Values.nfs.path }} #       